apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf-deployment
  labels:
    app: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:2.32.1
        ports:
        - containerPort: 3005
        envFrom: 
          - configMapRef:
              name:  audiobookshelf-configmap
        
        volumeMounts:
          - mountPath: "/app/audiobooks-data" 
            name: audiobooks-data
          - mountPath: "/app/podcasts-data" 
            name: podcasts-data
          - mountPath: "/app/config-data" 
            name:  config-data
          - mountPath: "/app/metadata" 
            name: metadata
      
      volume:
        - name: audiobooks-data
          persistentVolumeClaim:
            claimName: audiobooks-data
        - name: podcasts-data
          persistentVolumeClaim:
            claimName: podcasts-data
        - name: config-data
          persistentVolumeClaim:
            claimName: config-data
        - name: metadata
          persistentVolumeClaim:
            claimName: metadata
        
        
