apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf-deployment
  labels:
    app: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:2.32.1
        ports:
        - containerPort: 3005
        envFrom: 
          - configMapRef:
              name:  audiobookshelf-configmap
        
        volumeMounts:
          - mountPath: "/audiobooks" 
            name: audiobooks-data
          - mountPath: "/podcasts" 
            name: podcasts-data
          - mountPath: "/config" 
            name:  audiobookshelf-configdata
          - mountPath: "/metadata" 
            name: audiobookshelf-metadata
      
      volume:
        - name: audiobooks-data
          persistentVolumeClaim:
            claimName: audiobooks-data
        - name: podcasts-data
          persistentVolumeClaim:
            claimName: podcasts-data
        - name:  audiobookshelf-configdata
          persistentVolumeClaim:
            claimName:  audiobookshelf-configdata
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata
