apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf-deployment
  labels:
    app: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      # securityContext:
      #   fsGroup: 1000
      #   runAsUser: 1000
      #   runAsGroup: 1000

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.32.1
          ports:
            - containerPort: 3005
              protocol: TCP
          envFrom: 
            - configMapRef:
                name:  audiobookshelf-configmap
          volumeMounts:
            - mountPath: "/app/audiobooks" 
              name: audiobooks-data
            - mountPath: "/app/podcasts" 
              name: podcasts-data
            - mountPath: "/app/config" 
              name:  audiobookshelf-configdata
            - mountPath: "/app/metadata" 
              name: audiobookshelf-metadata
      restartPolicy: Always
      volumes:
        - name: audiobooks-data
          persistentVolumeClaim:
            claimName: audiobooks-data
        - name: podcasts-data
          persistentVolumeClaim:
            claimName: podcasts-data
        - name:  audiobookshelf-configdata
          persistentVolumeClaim:
            claimName:  audiobookshelf-configdata
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata
